import test from 'node:test';
import assert from 'node:assert/strict';
import {createRoom,applyAction,advance,viewRoom,maxBid,GameError} from '../.test-build/engine.js';
import {CATALOG,CATALOG_BY_ID} from '../.test-build/catalog.js';
import {simulateDuel} from '../.test-build/combat.js';
import {STAT_KEYS} from '../.test-build/types.js';
const NOW=1_000_000;
const action=(type,extra={})=>({type,requestId:crypto.randomUUID(),...extra});
function room(overrides={}){return createRoom('ABC234','host-session','Host',{maxPlayers:2,teamSize:3,marketSize:6,auctionSeconds:5,events:false,...overrides},'friends',NOW,31415)}
function withTwo(overrides={}){const r=room(overrides);applyAction(r,'other-session',action('join',{name:'Guest'}),NOW);applyAction(r,'other-session',action('ready'),NOW);applyAction(r,'host-session',action('start'),NOW);advance(r,NOW+4000);return r;}
test('catalog: 112 unique portraits, 8 universes and all 6 ranks; normalized numeric stats',()=>{
 assert.equal(CATALOG.length,112);assert.equal(new Set(CATALOG.map(c=>c.id)).size,112);assert.equal(new Set(CATALOG.map(c=>c.universe)).size,8);assert.equal(new Set(CATALOG.map(c=>c.rank)).size,6);
 for(const c of CATALOG){assert.equal(Object.keys(c.stats).length,8);for(const s of Object.values(c.stats))assert.ok(Number.isFinite(s)&&s>=0&&s<=100);}
});
test('room settings and membership are validated',()=>{assert.throws(()=>room({budget:-1}));assert.throws(()=>room({teamSize:4}));assert.throws(()=>room({universes:[]}));const r=withTwo();assert.throws(()=>applyAction(r,'hacker',action('bid',{amount:10,expectedRound:1}),NOW+4500));assert.throws(()=>applyAction(r,'other-session',action('skipBattle'),NOW+4500));});
test('public bidding preserves budget reserve and rejects invalid money',()=>{const r=withTwo();const me=r.players[0];assert.equal(maxBid(r,me),98);for(const amount of [-1,0,1.5,101,99,Infinity,NaN])assert.throws(()=>applyAction(r,'host-session',action('bid',{amount,expectedRound:1}),NOW+4500));applyAction(r,'host-session',action('bid',{amount:60,expectedRound:1}),NOW+4500);assert.equal(r.auction.bid,60);assert.equal(me.budget,100);assert.throws(()=>applyAction(r,'host-session',action('bid',{amount:61,expectedRound:1}),NOW+4600));assert.throws(()=>applyAction(r,'other-session',action('bid',{amount:59,expectedRound:1}),NOW+4600));});
test('idempotent bid retries do not duplicate sale or money',()=>{const r=withTwo();const bid=action('bid',{amount:50,expectedRound:1});applyAction(r,'host-session',bid,NOW+4500);applyAction(r,'host-session',bid,NOW+4800);assert.equal(r.auction.bids.length,1);advance(r,r.auction.endsAt+1);assert.equal(r.players[0].budget,50);assert.equal(r.players[0].roster.length,1);advance(r,NOW+9300);assert.equal(r.players[0].roster.length,1);});
test('expired and stale-round bids cannot change a sale',()=>{const r=withTwo();applyAction(r,'host-session',action('bid',{amount:7,expectedRound:1}),NOW+4500);assert.throws(()=>applyAction(r,'other-session',action('bid',{amount:20,expectedRound:1}),r.auction.endsAt+1));assert.equal(r.players[0].budget,93);assert.throws(()=>applyAction(r,'other-session',action('bid',{amount:20,expectedRound:99}),NOW+4500));});
test('anti-snipe extends by three seconds and has a hard deadline',()=>{const r=withTwo();const end=r.auction.endsAt;applyAction(r,'host-session',action('bid',{amount:2,expectedRound:1}),end-500);assert.equal(r.auction.endsAt,end+2500);for(let i=0;i<20;i++){const p=i%2===0?'other-session':'host-session';applyAction(r,p,action('bid',{amount:3+i,expectedRound:1}),r.auction.endsAt-100)}assert.ok(r.auction.endsAt<=r.auction.startedAt+60000)});
test('sealed bids are private; ties go to the earliest offer',()=>{const r=withTwo({auctionMode:'sealed'});applyAction(r,'host-session',action('bid',{amount:30,expectedRound:1}),NOW+4100);applyAction(r,'other-session',action('bid',{amount:30,expectedRound:1}),NOW+4200);const view=viewRoom(r,'host-session',NOW+4300);assert.equal(view.auction.bid,0);assert.equal(view.auction.leader,null);assert.equal(view.auction.bids.length,0);assert.equal(view.auction.myBid,30);assert.equal(view.auction.bidCount,2);assert.equal('sealed' in view.auction,false);advance(r,r.auction.endsAt+1);assert.equal(r.lastSale.playerId,r.players[0].id);assert.equal(r.players[0].budget,70)});
test('hidden information cannot leak via room snapshots or deck previews',()=>{const r=withTwo();const v=viewRoom(r,'host-session',NOW+4500);const json=JSON.stringify(v);assert.ok(!json.includes('host-session'));assert.equal('seed' in v,false);assert.equal('deck' in v,false);assert.equal('receipts' in v,false);assert.equal(v.cards[r.auction.characterId].stats,undefined);assert.equal(v.cards[r.auction.characterId].scout.power,undefined);assert.throws(()=>viewRoom(r,'stranger',NOW+4500));});
test('all information modes return only the intended data',()=>{for(const visibility of ['partial','hidden','expert','approximate','full']){const r=withTwo({visibility});const c=viewRoom(r,'host-session',NOW+4500).cards[r.auction.characterId];if(visibility==='full')assert.ok(c.stats);else assert.equal(c.stats,undefined);if(visibility==='approximate')assert.equal(Object.keys(c.scout).length,8);if(visibility==='hidden'||visibility==='expert')assert.equal(c.scout,undefined)}});
// debug is intentionally rejected even in a development build for friend rooms.
test('debug authorization requires both dev build and training mode',()=>{const r=withTwo();assert.throws(()=>applyAction(r,'host-session',action('debug:budget'),NOW+4500,true));const t=createRoom('ABC235','host-session','Host',{maxPlayers:2},'training',NOW,42);assert.throws(()=>applyAction(t,'host-session',action('debug:budget'),NOW,false));applyAction(t,'host-session',action('debug:budget'),NOW,true);assert.equal(t.players[0].budget,200)});
test('20 full games: unique rosters, conserved budgets, secret formations, matches and rematch',()=>{for(let seed=1;seed<=20;seed++){
 const r=createRoom('ABC234','host-session','Host',{maxPlayers:2+seed%5,teamSize:seed%2?3:5,marketSize:12,auctionSeconds:5,formationSeconds:20},'training',NOW,seed);let now=NOW,steps=0;
 while(r.phase!=='formation'&&steps++<3000){now+=700;advance(r,now)}assert.equal(r.phase,'formation');assert.equal(new Set(r.players.flatMap(p=>p.roster.map(x=>x.characterId))).size,r.players.length*r.settings.teamSize);
 for(const p of r.players){assert.equal(p.roster.length,r.settings.teamSize);assert.ok(p.budget>=0);assert.equal(p.budget+p.roster.reduce((n,x)=>n+x.price,0),r.settings.budget)}
 const own=r.players[0];const snapshot=viewRoom(r,'host-session',now);assert.ok(snapshot.players.slice(1).every(p=>p.formation.length===0));assert.equal(snapshot.players[0].formation.length,r.settings.teamSize);
 assert.throws(()=>applyAction(r,'host-session',action('lock',{formation:Array(r.settings.teamSize).fill(own.roster[0].characterId)}),now));
 applyAction(r,'host-session',action('lock',{formation:own.formation}),now);advance(r,now+1);assert.equal(r.phase,'battle');assert.equal(r.matches.length,r.players.length*(r.players.length-1)/2);for(const m of r.matches){assert.equal(m.scoreA+m.scoreB,r.settings.teamSize);assert.ok(m.winner===m.a||m.winner===m.b)}
 assert.ok(viewRoom(r,'host-session',now+1).cards[own.formation[0]].stats);
 advance(r,r.phaseEndsAt+1);assert.equal(r.phase,'results');applyAction(r,'host-session',action('rematch'),r.phaseEndsAt+2);assert.equal(r.phase,'lobby');assert.ok(r.players.every(p=>p.budget===r.settings.budget&&!p.roster.length));
}});
test('combat is deterministic and matchup-based; lower tiers and lower totals can win',()=>{assert.deepEqual(simulateDuel('goku','naruto',2,42),simulateDuel('goku','naruto',2,42));let lowerTier=0,lowerSum=0;const examples=[];for(const a of CATALOG.filter(c=>c.rank==='A'))for(const b of CATALOG.filter(c=>c.rank==='S'))for(let slot=0;slot<5;slot++){const d=simulateDuel(a.id,b.id,slot,42);if(d.winner==='a'){lowerTier++;if(Object.values(a.stats).reduce((n,x)=>n+x,0)<Object.values(b.stats).reduce((n,x)=>n+x,0))lowerSum++;if(examples.length<3)examples.push(`${a.name} beats ${b.name} at slot ${slot+1}`)}}assert.ok(lowerTier>10);assert.ok(lowerSum>10);console.log({lowerTierWins:lowerTier,lowerSumWins:lowerSum,examples});});
test('leaving transfers host and does not invalidate an active bid',()=>{const r=withTwo();applyAction(r,'host-session',action('bid',{amount:17,expectedRound:1}),NOW+4500);applyAction(r,'host-session',action('leave'),NOW+4700);assert.equal(r.hostId,r.players[1].id);advance(r,r.auction.endsAt+1);assert.equal(r.players[0].budget,83);assert.equal(r.players[0].roster.length,1);});
test('a departing player is actually replaced by a bidding bot',()=>{const r=withTwo();applyAction(r,'host-session',action('leave'),NOW+4100);let now=NOW+4200;for(let i=0;i<100&&r.phase!=='formation';i++){now+=1000;advance(r,now)}assert.ok(r.players[0].roster.some(x=>!x.reinforcement));});
test('combat health never increases during the finishing animation',()=>{for(let i=0;i<CATALOG.length-1;i++){const d=simulateDuel(CATALOG[i].id,CATALOG[i+1].id,i%5,42);let a=100,b=100;for(const f of d.frames){assert.ok(f.a<=a&&f.b<=b);a=f.a;b=f.b;}}});
