'use client';
import {useState} from 'react';
import {Search,X,SlidersHorizontal,BookOpen,Swords,Shield,Wind,Brain,Heart,Compass} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CharacterCard,StatBlock,Passive,RoleIcon} from './CharacterCard';
import {Choice} from './Setup';
import {type CardData,UNIVERSES,ROLE_LABELS,ROLE_DESCRIPTIONS} from '@/lib/game/types';
export function Catalog({cards,onCard}:{cards:CardData[];onCard:(c:CardData)=>void}){
 const [query,setQuery]=useState('');const [universe,setUniverse]=useState('all');const [role,setRole]=useState('all');
 const filtered=cards.filter(c=>(universe==='all'||c.universe===universe)&&(role==='all'||c.role===role)&&c.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="catalog-layout page-enter"><div className="catalog-header"><div><p className="eyebrow">APPRENEZ À RECONNAÎTRE LE TALENT</p><h1>Le carnet<br/><em>du recruteur.</em></h1></div><p>{cards.length} combattants. 8 univers.<br/>Les bonnes affaires se préparent.</p></div><div className="catalog-filters"><label className="search-input"><Search size={18}/><input placeholder="Chercher un combattant…" aria-label="Chercher un combattant" value={query} onChange={e=>setQuery(e.target.value)}/></label><Choice label="Univers" value={universe} options={[["all","Tous les univers"],...UNIVERSES.map(u=>[u.id,u.name] as [string,string])]} onChange={setUniverse}/><Choice label="Rôle" value={role} options={[["all","Tous les rôles"],...Object.entries(ROLE_LABELS)]} onChange={setRole}/></div><p className="catalog-count">{filtered.length} combattants <span>Les valeurs exactes restent secrètes jusqu’au combat.</span></p><div className="catalog-grid">{filtered.map(c=><CharacterCard key={c.id} card={c} onClick={()=>onCard(c)}/>)}</div>{!filtered.length&&<div className="empty-state"><Search size={30}/><h2>Aucun combattant trouvé.</h2><button className="secondary" onClick={()=>{setQuery('');setUniverse('all');setRole('all')}}>Effacer les filtres</button></div>}</div>
}
export function CardDetail({card,onClose}:{card:CardData;onClose:()=>void}){return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="card-detail-dialog"><DialogHeader><DialogTitle>{card.name}</DialogTitle><DialogDescription>{card.epithet}</DialogDescription></DialogHeader><div className="card-detail"><CharacterCard card={card} variant="auction" priority/><div><div className="role-detail"><RoleIcon role={card.role} size={22}/><strong>{ROLE_LABELS[card.role]}</strong><p>{ROLE_DESCRIPTIONS[card.role]}</p></div><StatBlock card={card}/><Passive card={card}/></div></div></DialogContent></Dialog>}
export function Rules({onClose}:{onClose:()=>void}){return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="rules-dialog"><DialogHeader><p className="eyebrow">UNE MINUTE POUR COMPRENDRE</p><DialogTitle className="modal-title">Recrutez malin.<br/>Gagnez ensemble.</DialogTitle><DialogDescription>Le nom fait monter l’enchère. Vos choix font gagner le match.</DialogDescription></DialogHeader><ol className="rules-steps"><li><span>01</span><div><h3>Un budget, une équipe.</h3><p>Enchérissez sur les personnages révélés. La meilleure offre remporte le lot. Gardez 1 M par place libre ; les recrues les plus modestes disponibles complètent les équipes inachevées.</p></div></li><li><span>02</span><div><h3>Gardez vos cartes en main.</h3><p>Placez secrètement vos recrues. Rempart renforce la résistance, Duel la technique, Assaut la puissance. En équipe de 5, Tactique et Dernier souffle ajoutent deux options.</p></div></li><li><span>03</span><div><h3>Chaque duel compte.</h3><p>Slot 1 contre slot 1, puis les suivants. La majorité des duels gagne le match. À plusieurs joueurs, tout le monde affronte tout le monde.</p></div></li></ol><div className="counter-guide"><h3>Un rôle peut faire la différence.</h3><div>{([['tank','attacker'],['attacker','support'],['support','assassin'],['assassin','controller'],['controller','tank']] as const).map(([a,b])=><div key={a}><RoleIcon role={a}/><span>{ROLE_LABELS[a]}</span><span className="beats">prend l’avantage sur</span><strong>{ROLE_LABELS[b]}</strong></div>)}</div><p>Le polyvalent n’a pas de contre direct. Un avantage de rôle ne garantit pas la victoire.</p></div><p className="rules-normalization">Les statistiques sont équilibrées pour ce crossover, indépendamment de la puissance canonique. Tous les univers peuvent gagner.</p><button className="primary full-width" onClick={onClose}>J’ai compris. Place au jeu.</button></DialogContent></Dialog>}
