'use client';
import {useEffect,useState} from 'react';
import {LockKeyhole,Check,ArrowLeftRight,Clock,Shield,Swords,Brain,Flame,Wind} from 'lucide-react';
import {CharacterCard,RoleIcon} from './CharacterCard';
import {Avatar} from './Lobby';
import {SLOTS,ROLE_LABELS,type RoomView,type Action,type CardData} from '@/lib/game/types';
const SLOT_ICONS=[Shield,Swords,Flame,Brain,Wind];
export default function Formation({room,act,busy,now,onCard}:{room:RoomView;act:(a:Partial<Action>)=>Promise<unknown>;busy:boolean;now:number;onCard:(c:CardData)=>void}){
 const me=room.players.find(p=>p.id===room.meId)!;const [order,setOrder]=useState(me.formation);const [selected,setSelected]=useState<number|null>(null);const [drag,setDrag]=useState<number|null>(null);const [saving,setSaving]=useState(false);const time=Math.max(0,Math.ceil((room.phaseEndsAt-now)/1000));
 useEffect(()=>{if(me.locked)setOrder(me.formation)},[me.locked]);
 async function swap(a:number,b:number){if(a===b||me.locked||saving)return;const next=[...order];[next[a],next[b]]=[next[b],next[a]];setOrder(next);setSelected(null);setSaving(true);const result=await act({type:'formation',formation:next});if(!result)setOrder(me.formation);setSaving(false);}
 const click=(i:number)=>{if(me.locked||saving)return;if(selected===null)setSelected(i);else if(selected===i)setSelected(null);else void swap(selected,i)};
 return <div className="formation-layout page-enter"><div className="formation-heading"><div><p className="eyebrow">LE TALENT NE SUFFIT PAS</p><h1>La bonne place.<br/><em>Le bon adversaire.</em></h1><p className="section-description">Sélectionnez deux cartes pour échanger leurs positions.<br/>Chaque emplacement apporte un avantage différent.</p></div><div className="formation-clock"><Clock size={20}/><strong>{time}<span>s</span></strong><small>POUR COMPOSER</small></div></div><div className="formation-slots">{order.map((id,i)=>{const c=room.cards[id],Icon=SLOT_ICONS[i];return <div className={`formation-slot ${selected===i?'slot-selected':''}`} key={i} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)void swap(drag,i);setDrag(null)}}><div className="slot-label"><span>0{i+1}</span><Icon size={16}/><h2>{SLOTS[i].name}</h2></div><div draggable={!me.locked&&!saving} onDragStart={()=>setDrag(i)} onDragEnd={()=>setDrag(null)}><CharacterCard card={c} variant="placement" selected={selected===i} onClick={()=>click(i)} price={me.roster.find(x=>x.characterId===id)?.price}/></div><p className="slot-bonus">{SLOTS[i].short}</p><button className="text-button" onClick={()=>onCard(c)}>Voir le scouting</button></div>})}</div><div className="formation-bottom"><div className="formation-instruction"><LockKeyhole size={22}/><span><strong>{me.locked?'Votre composition est verrouillée.':'Votre stratégie reste secrète.'}</strong><small>{me.locked?'Les autres équipes ne la voient pas encore.':'Au terme du chrono, la composition affichée sera retenue.'}</small></span></div><button className="primary" disabled={busy||saving||me.locked} onClick={()=>void act({type:'lock',formation:order})}>{me.locked?<Check size={18}/>:<LockKeyhole size={18}/>} {me.locked?'Composition verrouillée':'Verrouiller mon équipe'}</button></div><section className="opponent-rosters"><div className="panel-heading"><h2>Observez vos adversaires</h2><span>Leur ordre reste secret.</span></div>{room.players.filter(p=>p.id!==me.id).map(p=><div key={p.id} className="opponent-row"><div className="opponent-name"><Avatar name={p.name} color={p.color} bot={p.bot}/><strong>{p.name}</strong><span className={p.locked?'ready-status':''}>{p.locked?'Prêt':'Compose…'}</span></div><div className="opponent-cards">{p.roster.map(x=><button key={x.characterId} className="opponent-mini" onClick={()=>onCard(room.cards[x.characterId])}><img src={room.cards[x.characterId].portrait} alt="" loading="lazy"/><span>{room.cards[x.characterId].name}<small>{ROLE_LABELS[room.cards[x.characterId].role]}</small></span></button>)}</div></div>)}</section></div>
}
