'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {toast} from 'sonner';
import type {Action,CardData,RoomView,Settings} from '@/lib/game/types';
export function useGame(){
 const [room,setRoom]=useState<RoomView|null>(null);const [catalog,setCatalog]=useState<CardData[]>([]);const [busy,setBusy]=useState(false);const [connected,setConnected]=useState(true);const [restoring,setRestoring]=useState(true);const [joinCode,setJoinCode]=useState('');const [clock,setClock]=useState(Date.now());const [muted,setMuted]=useState(false);
 const current=useRef(room);const offset=useRef(0);const lock=useRef(false);const context=useRef<AudioContext|null>(null);const mutedRef=useRef(false);current.current=room;mutedRef.current=muted;
 const accept=useCallback((r:RoomView|null)=>{if(!r)return;const prev=current.current;if(prev&&prev.code===r.code&&prev.version>r.version)return;offset.current=r.serverNow-Date.now();current.current=r;setRoom(r);setConnected(true);localStorage.setItem('mm:lastRoom',r.code);history.replaceState(null,'',`?room=${r.code}`)},[]);
 const sound=useCallback((kind:string)=>{if(mutedRef.current)return;try{if(!context.current){const AC=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;context.current=new AC()}const ctx=context.current;if(ctx.state==='suspended')void ctx.resume();const notes=kind==='victory'?[392,494,587,784]:kind==='rare'?[220,330,440,660]:kind==='bid'?[440,660]:kind==='critical'?[130,260]:kind==='hit'?[170]:[460];notes.forEach((freq,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain();const start=ctx.currentTime+i*.075;oscillator.type=kind==='hit'||kind==='critical'?'triangle':'sine';oscillator.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(kind==='hit'?.016:.034,start+.008);gain.gain.exponentialRampToValueAtTime(.0001,start+.17);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.19)});}catch{}},[]);
 async function request(data:Partial<Action>):Promise<{room:RoomView|null;error?:string}>{const body=JSON.stringify({...data,requestId:data.requestId||crypto.randomUUID()});for(let attempt=0;attempt<2;attempt++){try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body,signal:AbortSignal.timeout(10000)});const result=await res.json() as {room:RoomView|null;error?:string};if(!res.ok)throw Object.assign(new Error(result.error||'Action impossible.'),{handled:true});return result;}catch(e){if((e as {handled?:boolean}).handled||attempt===1)throw e;}}throw new Error('Connexion impossible.');}
 const act=useCallback(async(a:Partial<Action>)=>{if(lock.current)return null;lock.current=true;setBusy(true);try{const result=await request({...a,code:current.current?.code});accept(result.room);if(a.type==='bid'){sound('bid');navigator.vibrate?.(12);toast.success('Offre enregistrée.')}if(a.type==='lock'){sound('click');toast.success('Équipe verrouillée.')}return result.room||true;}catch(e){toast.error(e instanceof Error?e.message:'Connexion interrompue. Réessayez.');return null;}finally{lock.current=false;setBusy(false)}},[accept,sound]);
 const create=async(name:string,settings:Settings,training:boolean)=>{if(lock.current)return false;lock.current=true;setBusy(true);sound('click');try{const result=await request({type:'create',name,settings,mode:training?'training':'friends'});accept(result.room);localStorage.setItem('mm:name',name);return true;}catch(e){toast.error(e instanceof Error?e.message:'Création impossible.');return false;}finally{lock.current=false;setBusy(false)}};
 const join=async(name:string,code:string)=>{if(lock.current)return false;lock.current=true;setBusy(true);sound('click');try{const result=await request({type:'join',name,code:code.toUpperCase()});accept(result.room);localStorage.setItem('mm:name',name);setJoinCode('');return true;}catch(e){toast.error(e instanceof Error?e.message:'Connexion impossible.');return false;}finally{lock.current=false;setBusy(false)}};
 const leave=async()=>{const result=await act({type:'leave'});if(result){current.current=null;setRoom(null);localStorage.removeItem('mm:lastRoom');history.replaceState(null,'','/')}};
 useEffect(()=>{setMuted(localStorage.getItem('mm:muted')==='1');const code=new URLSearchParams(location.search).get('room')||localStorage.getItem('mm:lastRoom');let live=true;fetch('/api/game?catalog=1').then(r=>{if(!r.ok)throw new Error('Catalogue indisponible');return r.json() as Promise<{characters:CardData[]}>}).then(x=>{if(live)setCatalog(x.characters)}).catch(()=>toast.error('Le carnet des combattants ne répond pas. Rechargez la page.'));
  if(code&&/^[A-HJ-NP-Z2-9]{6}$/i.test(code)){fetch(`/api/game?code=${code.toUpperCase()}`).then(async r=>{if(!r.ok){if([401,403].includes(r.status)&&new URLSearchParams(location.search).has('room'))setJoinCode(code.toUpperCase());else if(r.status===404||r.status===410){localStorage.removeItem('mm:lastRoom');history.replaceState(null,'','/')}else if(r.status>=500){setConnected(false);setJoinCode(code.toUpperCase())}return null;}return r.json() as Promise<{room:RoomView}>}).then(x=>{if(live&&x?.room)accept(x.room)}).catch(()=>{if(live){setConnected(false);setJoinCode(code.toUpperCase())}}).finally(()=>{if(live)setRestoring(false)})}else setRestoring(false);return()=>{live=false}},[accept]);
 useEffect(()=>{if(!room)return;let disposed=false,timer:ReturnType<typeof setTimeout>;async function poll(){try{const res=await fetch(`/api/game?code=${room!.code}`,{signal:AbortSignal.timeout(7000)});const data=await res.json() as {room:RoomView;error:string};if(!disposed){if(res.ok)accept(data.room);else{setConnected(false);if([401,403,404,410].includes(res.status)){toast.error(data.error);current.current=null;setRoom(null);localStorage.removeItem('mm:lastRoom')}}}}catch{if(!disposed)setConnected(false)}finally{if(!disposed)timer=setTimeout(poll,document.hidden?2500:800)}}timer=setTimeout(poll,750);return()=>{disposed=true;clearTimeout(timer)}},[room?.code,accept]);
 useEffect(()=>{if(!room)return;const id=setInterval(()=>setClock(Date.now()+offset.current),100);return()=>clearInterval(id)},[!!room]);
 const previous=useRef({phase:'',round:0,leader:null as string|null});useEffect(()=>{if(!room)return;const p=previous.current;if(p.phase!==room.phase){if(room.phase==='auction')sound(room.cards[room.auction!.characterId]?.rank==='SS'?'rare':'click');if(room.phase==='sold')sound(room.lastSale?.playerId===room.meId?'victory':'click');}if(room.phase==='auction'&&p.leader===room.meId&&room.auction?.leader&&room.auction.leader!==room.meId){toast('Votre offre a été dépassée.');sound('critical')}previous.current={phase:room.phase,round:room.round,leader:room.auction?.leader||null}},[room?.phase,room?.round,room?.auction?.leader,sound]);
 const toggleMute=()=>{setMuted(x=>{localStorage.setItem('mm:muted',x?'0':'1');mutedRef.current=!x;return !x});if(muted)sound('click')};
 return {room,catalog,busy,connected,restoring,joinCode,setJoinCode,now:clock,muted,toggleMute,sound,act,create,join,leave};
}
