// Server-only catalogue. Never import this module into client components.
// Scores are editorial gameplay ratings, not measurements of canonical power.
import {type Character,type Role,type Rank,type Ability,type Stats,STAT_KEYS} from './types';
const BASE:Record<Rank,number>={D:39,C:47,B:56,A:64,S:72,SS:78};
const PROFILE:Record<Role,number[]>={attacker:[19,4,1,5,-8,-10,-1,3],tank:[7,-13,24,-3,-5,-8,-12,16],assassin:[10,22,-18,14,2,-6,-9,-10],controller:[-11,0,-8,13,17,23,4,-7],support:[-18,-3,0,7,15,11,4,14],balanced:[3,3,4,4,4,1,1,5]};
// name, rank, role, ability, specialty (stats), epithet. Profiles share the same
// normalized tier budget; the specialist vector reallocates, rather than adds, power.
type Seed=[string,Rank,Role,Ability,string,string];
const seeds:Record<string,Seed[]>={
'naruto':[
['Naruto','SS','balanced','resolve','stamina,power','Une volonté sans limite'],['Sasuke','SS','assassin','precision','technique,control','Le regard qui anticipe'],['Sakura','A','support','recovery','power,defense','La force de reconstruire'],['Kakashi','S','controller','adaptation','intelligence,technique','Toujours un coup d’avance'],['Itachi','S','controller','disruption','control,intelligence','Le calme avant l’illusion'],['Gaara','A','tank','bulwark','control,range','La défense absolue'],['Rock Lee','A','assassin','tempo','speed,technique','Le travail devient talent'],['Hinata','B','support','precision','technique,control','La précision silencieuse'],['Shikamaru','A','controller','adaptation','intelligence,control','La partie était déjà jouée'],['Neji','A','balanced','precision','technique,defense','Aucun angle mort'],['Tsunade','S','support','recovery','power,defense','La force d’une légende'],['Jiraiya','S','balanced','resolve','stamina,range','Le pari de l’expérience'],['Orochimaru','S','controller','disruption','technique,stamina','Impossible à prévoir'],['Madara','SS','attacker','burst','control,range','Une armée à lui seul']],
'dragon-ball':[
['Goku','SS','balanced','resolve','power,stamina','Toujours plus loin'],['Vegeta','SS','attacker','burst','power,technique','La fierté du prince'],['Gohan','S','attacker','burst','power,intelligence','Le potentiel déchaîné'],['Piccolo','A','controller','adaptation','intelligence,range','La sagesse du combat'],['Krillin','B','support','disruption','technique,intelligence','Le courage fait la différence'],['Trunks','S','assassin','precision','power,speed','Une lame venue du futur'],['Frieza','SS','attacker','precision','range,control','Une précision impitoyable'],['Cell','S','balanced','adaptation','technique,intelligence','L’ambition de la perfection'],['Majin Buu','SS','tank','recovery','stamina,defense','Une énergie inépuisable'],['Android 18','A','balanced','resolve','stamina,speed','L’efficacité sans détour'],['Android 17','A','tank','bulwark','stamina,control','Le gardien infatigable'],['Tien','B','controller','disruption','technique,control','La discipline avant tout'],['Yamcha','D','assassin','tempo','speed,technique','L’instinct du loup'],['Master Roshi','B','controller','adaptation','technique,intelligence','L’expérience est une arme']],
'one-piece':[
['Luffy','SS','attacker','resolve','stamina,control','La liberté ne se négocie pas'],['Zoro','S','attacker','precision','technique,stamina','Trois lames, une ambition'],['Nami','B','controller','adaptation','intelligence,range','Un temps d’avance'],['Sanji','S','assassin','tempo','speed,technique','Le feu dans les jambes'],['Usopp','C','controller','precision','range,intelligence','Le tir qui change tout'],['Chopper','B','support','recovery','defense,intelligence','Petit format, grand secours'],['Robin','A','controller','disruption','control,intelligence','Le savoir est une force'],['Franky','A','tank','bulwark','power,range','Solide comme l’acier'],['Brook','B','assassin','tempo','speed,control','Une seconde vie pour briller'],['Jinbe','S','tank','bulwark','technique,defense','Le courant tranquille'],['Law','S','controller','precision','control,technique','Le chirurgien du matchup'],['Ace','S','attacker','burst','range,power','La flamme ne cède pas'],['Shanks','SS','balanced','adaptation','control,technique','La présence d’un empereur'],['Boa Hancock','S','controller','disruption','control,speed','Une entrée pétrifiante']],
'bleach':[
['Ichigo','SS','attacker','burst','power,speed','L’instinct de protéger'],['Rukia','A','controller','disruption','control,technique','Un calme glacial'],['Orihime','B','support','recovery','defense,control','Le refus de céder'],['Renji','A','attacker','resolve','range,stamina','Une détermination mordante'],['Byakuya','S','controller','precision','range,technique','La précision de mille lames'],['Kenpachi','SS','attacker','resolve','power,stamina','La joie du duel'],['Toshiro','S','controller','disruption','range,control','Le froid impose son rythme'],['Yoruichi','S','assassin','tempo','speed,technique','Un éclair dans la nuit'],['Urahara','S','support','adaptation','intelligence,technique','Un plan dans chaque plan'],['Aizen','SS','controller','adaptation','intelligence,control','La maîtrise de l’illusion'],['Grimmjow','A','assassin','burst','power,speed','L’instinct du prédateur'],['Ulquiorra','S','balanced','recovery','defense,range','La sérénité du vide'],['Chad','B','tank','bulwark','power,defense','Le poing qui protège'],['Uryu','A','assassin','precision','range,intelligence','Une flèche, une ouverture']],
'jujutsu-kaisen':[
['Yuji','A','attacker','resolve','power,stamina','Jamais à terre'],['Megumi','A','controller','adaptation','intelligence,control','Le terrain lui appartient'],['Nobara','B','controller','precision','technique,range','Une cible, aucun doute'],['Gojo','SS','controller','bulwark','defense,speed','L’infini comme terrain de jeu'],['Sukuna','SS','attacker','precision','technique,control','Une menace sans répit'],['Maki','A','assassin','precision','power,technique','Les armes parlent pour elle'],['Toge','B','support','disruption','control,range','Chaque mot compte'],['Panda','B','tank','recovery','defense,stamina','Plus solide qu’il n’y paraît'],['Yuta','S','balanced','recovery','power,control','Une réserve insoupçonnée'],['Nanami','A','balanced','precision','technique,intelligence','Le point faible est calculé'],['Todo','A','tank','adaptation','intelligence,power','La surprise au corps à corps'],['Mahito','S','controller','disruption','control,stamina','Les règles changent au contact'],['Geto','S','controller','adaptation','range,intelligence','Mille réponses possibles'],['Toji','S','assassin','tempo','power,speed','Aucun bruit, aucune erreur']],
'hunter-x-hunter':[
['Gon','S','attacker','burst','power,stamina','Tout miser sur un poing'],['Killua','S','assassin','tempo','speed,technique','Le réflexe avant la pensée'],['Kurapika','S','controller','disruption','control,intelligence','Les chaînes du jugement'],['Leorio','D','support','recovery','stamina,intelligence','Le cœur avant la puissance'],['Hisoka','S','controller','adaptation','technique,control','Chaque duel est un spectacle'],['Chrollo','S','controller','adaptation','intelligence,technique','Une réponse pour chaque combat'],['Netero','SS','balanced','precision','speed,technique','La maîtrise au-delà du temps'],['Meruem','SS','balanced','adaptation','intelligence,power','Apprendre, puis dominer'],['Biscuit','A','tank','recovery','power,technique','Ne vous fiez pas aux apparences'],['Illumi','A','controller','disruption','control,technique','La menace invisible'],['Feitan','A','assassin','burst','speed,technique','La riposte brûlante'],['Knuckle','B','tank','resolve','stamina,control','Chaque échange a un prix'],['Kite','A','balanced','precision','technique,range','Le bon outil au bon moment'],['Neferpitou','S','assassin','recovery','speed,power','L’instinct à l’état pur']],
'demon-slayer':[
['Tanjiro','S','balanced','resolve','technique,intelligence','L’odorat de la victoire'],['Nezuko','A','tank','recovery','power,stamina','La douceur et la fureur'],['Zenitsu','A','assassin','tempo','speed,power','Un éclair suffit'],['Inosuke','A','attacker','burst','power,speed','L’instinct sans détour'],['Giyu','S','tank','bulwark','technique,defense','Le calme de l’eau'],['Shinobu','A','assassin','precision','technique,intelligence','La précision du papillon'],['Rengoku','S','attacker','resolve','power,stamina','Un cœur enflammé'],['Tengen','S','assassin','tempo','speed,range','L’art du rythme'],['Mitsuri','S','attacker','recovery','power,range','Une force inattendue'],['Muichiro','S','assassin','disruption','speed,technique','Perdu dans la brume'],['Sanemi','S','attacker','burst','power,stamina','Une tempête inflexible'],['Gyomei','SS','tank','bulwark','power,technique','Le pilier inébranlable'],['Akaza','SS','assassin','adaptation','technique,stamina','Le duel comme obsession'],['Muzan','SS','controller','recovery','control,stamina','L’ombre persiste']],
'my-hero-academia':[
['Deku','S','balanced','adaptation','power,intelligence','Analyser, puis se dépasser'],['Bakugo','S','attacker','burst','power,speed','L’explosion du talent'],['Todoroki','S','controller','disruption','range,control','Deux forces, un équilibre'],['Uraraka','B','support','disruption','control,speed','Changer le poids du combat'],['Iida','B','assassin','tempo','speed,stamina','La vitesse avec méthode'],['Tsuyu','C','support','adaptation','control,speed','S’adapter à tous les terrains'],['Kirishima','A','tank','bulwark','defense,stamina','Impossible à briser'],['Yaoyorozu','B','support','adaptation','intelligence,range','La solution se construit'],['Tokoyami','A','controller','burst','control,range','L’ombre prend le relais'],['All Might','SS','attacker','resolve','power,defense','Le symbole se tient debout'],['Aizawa','S','controller','disruption','control,intelligence','Éteindre l’avantage adverse'],['Hawks','S','assassin','tempo','speed,range','Un temps d’avance dans les airs'],['Dabi','A','attacker','burst','range,power','Une flamme à double tranchant'],['Shigaraki','SS','controller','disruption','control,power','Le contact qui renverse tout']]
};
export function slug(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export const CATALOG:Character[]=Object.entries(seeds).flatMap(([universe,rows])=>rows.map(([name,rank,role,ability,special,epithet])=>{
 const focus=special.split(',');const stats={} as Stats;
 STAT_KEYS.forEach((key,i)=>stats[key]=Math.max(18,Math.min(98,BASE[rank]+PROFILE[role][i]+(focus.includes(key)?9:-3))));
 const baseValue=Math.round(({D:3,C:6,B:11,A:18,S:27,SS:38}[rank])+(stats.technique+stats.intelligence-120)/20);
 return {id:slug(name),name,universe,rank,role,ability,epithet,stats,baseValue,portrait:`/portraits/${slug(name)}.webp`,traits:focus.map(s=>s==='stamina'?'Endurant':s==='speed'?'Vif':s==='intelligence'?'Stratège':s==='technique'?'Précis':s==='range'?'Longue portée':s==='control'?'Perturbateur':s==='defense'?'Solide':'Explosif'),loreTier:Object.keys(BASE).indexOf(rank)+1};
}));
// Low-rank, named characters remain meaningful bargains alongside superstars.
export const CATALOG_BY_ID=Object.fromEntries(CATALOG.map(c=>[c.id,c]));
