export const STAT_KEYS = ['power','speed','defense','technique','intelligence','control','range','stamina'] as const;
export type Stat = typeof STAT_KEYS[number];
export type Stats = Record<Stat, number>;
export type Rank = 'D'|'C'|'B'|'A'|'S'|'SS';
export type Role = 'attacker'|'tank'|'assassin'|'controller'|'support'|'balanced';
export type Visibility = 'partial'|'full'|'approximate'|'hidden'|'expert';
export type Phase = 'lobby'|'reveal'|'auction'|'sold'|'formation'|'battle'|'results';
export type Ability = 'burst'|'bulwark'|'precision'|'adaptation'|'disruption'|'resolve'|'tempo'|'recovery';
export interface Character { id:string; name:string; universe:string; rank:Rank; role:Role; portrait:string; epithet:string; ability:Ability; traits:string[]; stats:Stats; baseValue:number; loreTier:number; }
export interface CardData {id:string;name:string;universe:string;rank:Rank;role:Role;portrait:string;epithet:string;ability:Ability;traits:string[];scout?:Partial<Record<Stat,number|string>>;stats?:Stats}
export interface Settings {maxPlayers:number;teamSize:number;budget:number;marketSize:number;auctionSeconds:number;visibility:Visibility;auctionMode:'public'|'sealed';universes:string[];events:boolean;antiSnipe:boolean;formationSeconds:number;}
export interface Purchase {characterId:string;price:number;round:number;reinforcement?:boolean}
export interface Player {id:string;sid:string;name:string;color:number;bot:boolean;ready:boolean;budget:number;roster:Purchase[];formation:string[];locked:boolean;left:boolean;lastSeen:number;}
export interface Bid {playerId:string;amount:number;at:number}
export interface Auction {characterId:string;round:number;endsAt:number;startedAt:number;bid:number;leader:string|null;bids:Bid[];sealed:Record<string,Bid>;botAt:number;event:string|null;}
export interface CombatFrame {a:number;b:number;actor:'a'|'b';label:string;critical:boolean}
export interface Duel {slot:number;aId:string;bId:string;winner:'a'|'b';scoreA:number;scoreB:number;hpA:number;hpB:number;frames:CombatFrame[];reasonsA:string[];reasonsB:string[];statsA:Stats;statsB:Stats;}
export interface Match {a:string;b:string;scoreA:number;scoreB:number;winner:string;duels:Duel[]}
export interface Award {title:string;playerId:string;characterId:string;value:string}
export interface Room {code:string;version:number;hostId:string;mode:'friends'|'training';phase:Phase;settings:Settings;players:Player[];deck:string[];pool:string[];round:number;auction:Auction|null;phaseEndsAt:number;lastSale:{characterId:string;playerId:string|null;price:number}|null;matches:Match[];awards:Award[];seed:number;createdAt:number;updatedAt:number;receipts:Record<string,string>;log:{id:string;text:string;kind:string;at:number}[];}
export type PublicPlayer=Omit<Player,'sid'|'lastSeen'|'formation'> & {formation:string[];online:boolean};
export interface RoomView {code:string;version:number;hostId:string;mode:Room['mode'];phase:Phase;settings:Settings;players:PublicPlayer[];round:number;marketTotal:number;auction:Omit<Auction,'sealed'|'botAt'|'bids'> & {bids:Bid[];myBid:number;bidCount:number}|null;phaseEndsAt:number;lastSale:Room['lastSale'];matches:Match[];awards:Award[];log:Room['log'];meId:string;serverNow:number;cards:Record<string,CardData>;dev:boolean;}
export interface Action {type:string;requestId:string;expectedRound?:number;amount?:number;playerId?:string;formation?:string[];name?:string;settings?:Partial<Settings>;mode?:'training'|'friends';code?:string;characterId?:string;speed?:number;teams?:string[][];}
export const STAT_LABELS:Record<Stat,string>={power:'Puissance',speed:'Vitesse',defense:'Résistance',technique:'Technique',intelligence:'Intelligence',control:'Contrôle',range:'Portée',stamina:'Endurance'};
export const ROLE_LABELS:Record<Role,string>={attacker:'Attaquant',tank:'Tank',assassin:'Assassin',controller:'Contrôleur',support:'Support',balanced:'Polyvalent'};
export const ROLE_DESCRIPTIONS:Record<Role,string>={attacker:'Met la pression et brise les soutiens.',tank:'Absorbe la puissance des attaquants.',assassin:'Prend les contrôleurs de vitesse.',controller:'Contourne la garde des tanks.',support:'Récupère et résiste aux assassins.',balanced:'Régulier, sans contre extrême.'};
export const RANK_COLORS:Record<Rank,string>={D:'#a9abb9',C:'#b8ce9b',B:'#82b8e8',A:'#b6a0ec',S:'#f4c57a',SS:'#ead6a1'};
export const ABILITIES:Record<Ability,{name:string;description:string}>={burst:{name:'Percée',description:'+9 % de pression offensive en début de duel.'},bulwark:{name:'Rempart',description:'+12 % de défense contre la pression physique.'},precision:{name:'Point faible',description:'+10 % à l’efficacité technique.'},adaptation:{name:'Lecture du jeu',description:'+10 % à l’adaptation et au contrôle.'},disruption:{name:'Entrave',description:'Réduit de 8 % la vitesse adverse.'},resolve:{name:'Second souffle',description:'+13 % d’endurance, décisif dans les duels serrés.'},tempo:{name:'Initiative',description:'+12 % de vitesse au calcul du duel.'},recovery:{name:'Récupération',description:'+7 % de résistance et +9 % d’endurance.'}};
export const SLOTS=[{id:'frontline',name:'Rempart',short:'Résistance +15 % · puissance +5 %',boost:{defense:1.15,power:1.05}},{id:'duel',name:'Duel',short:'Technique +15 % · vitesse +5 %',boost:{technique:1.15,speed:1.05}},{id:'assault',name:'Assaut',short:'Puissance +15 % · résistance −5 %',boost:{power:1.15,defense:.95}},{id:'tactical',name:'Tactique',short:'Intelligence +15 % · contrôle +15 %',boost:{intelligence:1.15,control:1.15}},{id:'laststand',name:'Dernier souffle',short:'Endurance +18 % · bonus si mené',boost:{stamina:1.18}}] as const;
export const UNIVERSES=[{id:'naruto',name:'Naruto',short:'NARUTO',color:'#f4ae5e'},{id:'dragon-ball',name:'Dragon Ball',short:'DRAGON BALL',color:'#f3c260'},{id:'one-piece',name:'One Piece',short:'ONE PIECE',color:'#77b7db'},{id:'bleach',name:'Bleach',short:'BLEACH',color:'#a09dea'},{id:'jujutsu-kaisen',name:'Jujutsu Kaisen',short:'JUJUTSU KAISEN',color:'#ac9fdc'},{id:'hunter-x-hunter',name:'Hunter × Hunter',short:'HUNTER × HUNTER',color:'#9ac99b'},{id:'demon-slayer',name:'Demon Slayer',short:'DEMON SLAYER',color:'#c67983'},{id:'my-hero-academia',name:'My Hero Academia',short:'MY HERO ACADEMIA',color:'#83c2b0'}];
export const DEFAULT_SETTINGS:Settings={maxPlayers:4,teamSize:3,budget:100,marketSize:18,auctionSeconds:15,visibility:'partial',auctionMode:'public',universes:UNIVERSES.map(u=>u.id),events:true,antiSnipe:true,formationSeconds:90};
